export const mockData = {
  users: [
    { id: 1, name: 'Admin User', email: 'admin@example.com', role: 'admin', status: 'active' },
    { id: 2, name: 'Customer User', email: 'customer@example.com', role: 'customer', status: 'active' },
  ],
  templates: [
    {
      id: 1,
      code: 'lang-man-hoa',
      name: 'Lãng Mạn Hoa',
      category: 'floral',
      component_name: 'lang-man-hoa',
      default_config_json: {
        primary_color: '#D98BA5',
        secondary_color: '#FFF7F9',
        font_heading: 'Playfair Display',
        font_body: 'Inter',
        music_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'
      },
      supported_sections_json: ['hero', 'intro', 'couple', 'story', 'events', 'gallery', 'bank', 'rsvp'],
      thumbnail_path: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=2069&auto=format&fit=crop',
      preview_image_path: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=2069&auto=format&fit=crop',
      is_premium: false,
      price: 0,
      status: 'active',
    },
    {
      id: 2,
      code: 'toi-gian-trang',
      name: 'Tối Giản Trắng',
      category: 'minimalist',
      component_name: 'toi-gian-trang',
      default_config_json: {
        primary_color: '#111827',
        secondary_color: '#FFFFFF',
        font_heading: 'Playfair Display',
        font_body: 'Inter'
      },
      supported_sections_json: ['hero', 'intro', 'couple', 'events', 'bank', 'rsvp'],
      thumbnail_path: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?q=80&w=2070&auto=format&fit=crop',
      preview_image_path: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?q=80&w=2070&auto=format&fit=crop',
      is_premium: false,
      price: 0,
      status: 'active',
    },
    {
      id: 3,
      code: 'truyen-thong-do',
      name: 'Truyền Thống Đỏ',
      category: 'traditional',
      component_name: 'truyen-thong-do',
      default_config_json: {
        primary_color: '#B91C1C',
        secondary_color: '#FFF1D6',
        font_heading: 'Playfair Display',
        font_body: 'Inter'
      },
      supported_sections_json: ['hero', 'intro', 'couple', 'events', 'gallery', 'bank', 'rsvp'],
      thumbnail_path: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=1974&auto=format&fit=crop',
      preview_image_path: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=1974&auto=format&fit=crop',
      is_premium: false,
      price: 0,
      status: 'active',
    },
    {
      id: 4,
      code: 'hoang-gia-vang',
      name: 'Hoàng Gia Vàng',
      category: 'luxury',
      component_name: 'hoang-gia-vang',
      default_config_json: {
        primary_color: '#C8A951',
        secondary_color: '#111111',
        font_heading: 'Cormorant Garamond',
        font_body: 'Inter'
      },
      supported_sections_json: ['hero', 'intro', 'events', 'bank'],
      thumbnail_path: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=2070&auto=format&fit=crop',
      preview_image_path: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=2070&auto=format&fit=crop',
      is_premium: true,
      price: 199000,
      status: 'active',
    },
    {
      id: 5,
      code: 'phim-anh-hien-dai',
      name: 'Phim Ảnh Hiện Đại',
      category: 'modern',
      component_name: 'phim-anh-hien-dai',
      default_config_json: {
        primary_color: '#111827',
        secondary_color: '#F8FAFC',
        font_heading: 'Inter',
        font_body: 'Inter'
      },
      supported_sections_json: ['hero', 'story', 'gallery', 'events', 'bank'],
      thumbnail_path: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?q=80&w=2070&auto=format&fit=crop',
      preview_image_path: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?q=80&w=2070&auto=format&fit=crop',
      is_premium: true,
      price: 150000,
      status: 'active',
    },
    {
      id: 6,
      code: 'moc-mac-xanh',
      name: 'Mộc Mạc Xanh',
      category: 'floral',
      component_name: 'moc-mac-xanh',
      default_config_json: {
        primary_color: '#2D4F1E',
        secondary_color: '#FDFCF8',
        accent_color: '#A3B18A',
        font_heading: 'Playfair Display',
        font_body: 'Inter'
      },
      supported_sections_json: ['hero', 'intro', 'couple', 'story', 'events', 'gallery', 'bank', 'rsvp', 'wishes'],
      thumbnail_path: 'https://images.unsplash.com/photo-1544833058-e70f9ca2bdc5?q=80&w=1974&auto=format&fit=crop',
      preview_image_path: 'https://images.unsplash.com/photo-1544833058-e70f9ca2bdc5?q=80&w=1974&auto=format&fit=crop',
      is_premium: true,
      price: 250000,
      status: 'active',
    },
    {
      id: 7,
      code: 'sang-trong-truyen-thong',
      name: 'Sang Trọng Truyền Thống',
      category: 'traditional',
      component_name: 'sang-trong-truyen-thong',
      default_config_json: {
        primary_color: '#8B0000',
        secondary_color: '#C8A951',
        font_heading: 'Playfair Display',
        font_body: 'Be Vietnam Pro'
      },
      supported_sections_json: ['hero', 'intro', 'couple', 'events', 'bank'],
      thumbnail_path: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=1974&auto=format&fit=crop',
      preview_image_path: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=1974&auto=format&fit=crop',
      is_premium: true,
      price: 300000,
      status: 'active',
    },
    {
      id: 8,
      code: 'phuong-hoang-lua',
      name: 'Phượng Hoàng Lửa',
      category: 'traditional',
      component_name: 'phuong-hoang-lua',
      default_config_json: {
        primary_color: '#B00000',
        secondary_color: '#F8E2AF',
        font_heading: 'Playfair Display',
        font_body: 'Be Vietnam Pro'
      },
      supported_sections_json: ['hero', 'intro', 'couple', 'events', 'bank'],
      thumbnail_path: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=1974&auto=format&fit=crop',
      preview_image_path: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=1974&auto=format&fit=crop',
      is_premium: true,
      price: 280000,
      status: 'active',
    },
    {
      id: 9,
      code: 'hien-dai-luc-bao',
      name: 'Hiện Đại Lục Bảo',
      category: 'modern',
      component_name: 'hien-dai-luc-bao',
      default_config_json: {
        primary_color: '#00B14F',
        secondary_color: '#F4F7F6',
        font_heading: 'Inter',
        font_body: 'Be Vietnam Pro'
      },
      supported_sections_json: ['hero', 'intro', 'events', 'gallery', 'bank', 'rsvp'],
      thumbnail_path: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=2069&auto=format&fit=crop',
      preview_image_path: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=2069&auto=format&fit=crop',
      is_premium: false,
      price: 0,
      status: 'active',
    }
  ],
  weddings: [
    {
      id: 1,
      user_id: 2,
      template_id: 6,
      slug: 'minh-anh-hoang-nam',
      title: 'Minh Anh & Hoàng Nam',
      bride_name: 'Minh Anh',
      groom_name: 'Hoàng Nam',
      bride_full_name: 'Nguyễn Thị Minh Anh',
      groom_full_name: 'Trần Hoàng Nam',
      bride_phone: '0987654321',
      groom_phone: '0123456789',
      bride_father_name: 'Nguyễn Văn A',
      bride_mother_name: 'Trần Thị B',
      groom_father_name: 'Trần Văn C',
      groom_mother_name: 'Lê Thị D',
      cover_image_path: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=2069&auto=format&fit=crop',
      intro_text: 'Tình yêu không phải là tìm thấy một ai đó hoàn hảo, mà là học cách nhìn thấy những điều tuyệt vời từ một người không hoàn hảo.',
      love_story: 'Chúng tôi quen nhau vào một ngày mùa thu nắng vàng tại ngôi trường đại học. Từ những người bạn xa lạ, chúng tôi đã cùng nhau đi qua biết bao kỷ niệm vui buồn...',
      wedding_date: '2026-12-20',
      lunar_date_text: 'Ngày 12 tháng 11 năm Bính Ngọ',
      music_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
      language: 'vi',
      theme_config_json: {
        primary_color: '#2D4F1E',
        secondary_color: '#FDFCF8',
        accent_color: '#A3B18A',
        font_heading: 'Playfair Display',
        font_body: 'Inter'
      },
      status: 'published',
      is_public: true,
      hide_watermark: false,
    }
  ],
  wedding_events: [
    {
      id: 1,
      wedding_id: 1,
      event_type: 'ceremony',
      title: 'Lễ Thành Hôn',
      event_time: '2026-12-20 11:30:00',
      venue_name: 'Trung tâm tiệc cưới Trống Đồng',
      address: '123 Cầu Giấy, Hà Nội',
      map_url: 'https://maps.google.com/?q=Trống+Đồng+Palace',
      latitude: 21.0285,
      longitude: 105.7891,
      note: 'Trang phục: Trắng, Kem, Xanh lá',
      sort_order: 1
    },
    {
      id: 2,
      wedding_id: 1,
      event_type: 'party',
      title: 'Tiệc Giao Lưu',
      event_time: '2026-12-20 18:00:00',
      venue_name: 'Khách sạn JW Marriott',
      address: '8 Đỗ Đức Dục, Mễ Trì, Nam Từ Liêm, Hà Nội',
      map_url: 'https://maps.google.com/?q=JW+Marriott+Hotel+Hanoi',
      latitude: 21.0091,
      longitude: 105.7876,
      note: 'Rất hân hạnh được đón tiếp!',
      sort_order: 2
    }
  ],
  wedding_photos: [
    { id: 1, wedding_id: 1, image_path: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=2070&auto=format&fit=crop', caption: 'Ảnh cưới ngoại cảnh', sort_order: 1 },
    { id: 2, wedding_id: 1, image_path: 'https://images.unsplash.com/photo-1520854221256-17451cc331bf?q=80&w=2070&auto=format&fit=crop', caption: 'Khoảnh khắc hạnh phúc', sort_order: 2 },
    { id: 3, wedding_id: 1, image_path: 'https://images.unsplash.com/photo-1544833058-e70f9ca2bdc5?q=80&w=1974&auto=format&fit=crop', caption: 'Bó hoa cưới', sort_order: 3 },
    { id: 4, wedding_id: 1, image_path: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?q=80&w=2070&auto=format&fit=crop', caption: 'Nụ cười rạng ngời', sort_order: 4 },
    { id: 5, wedding_id: 1, image_path: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=1974&auto=format&fit=crop', caption: 'Pre-wedding', sort_order: 5 },
    { id: 6, wedding_id: 1, image_path: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1974&auto=format&fit=crop', caption: 'Chú rể', sort_order: 6 },
  ],
  wedding_bank_accounts: [
    {
      id: 1,
      wedding_id: 1,
      owner_name: 'NGUYEN THI MINH ANH',
      bank_name: 'Vietcombank',
      bank_code: 'VCB',
      account_number: '012345678910',
      qr_image_path: 'https://img.vietqr.io/image/vcb-012345678910-compact.jpg',
      transfer_note: 'Mừng cưới Minh Anh',
      is_active: true,
      sort_order: 1
    },
    {
      id: 2,
      wedding_id: 1,
      owner_name: 'TRAN HOANG NAM',
      bank_name: 'MB Bank',
      bank_code: 'MB',
      account_number: '9876543210',
      qr_image_path: 'https://img.vietqr.io/image/mb-9876543210-compact.jpg',
      transfer_note: 'Mừng cưới Hoàng Nam',
      is_active: true,
      sort_order: 2
    }
  ],
  wedding_rsvps: [
    { id: 1, wedding_id: 1, guest_name: 'Nguyễn Tuấn', attendance_status: 'attending', guest_count: 2, message: 'Chúc hai bạn trăm năm hạnh phúc!' }
  ],
  wedding_wishes: [
    { id: 1, wedding_id: 1, guest_name: 'Hoàng Tuấn Anh', message: 'Chúc hai bạn mãi mãi hạnh phúc!', is_approved: true }
  ]
};
